// Generated; no network or private inputs.
window.INSTALL_CATALOG = {
  "repository": "BrownieCoder/proxy-rulesets",
  "branch": "main",
  "siteUrl": null,
  "services": [
    {
      "id": "siri-ai",
      "provider": "SiriAI",
      "name": "Siri AI / Apple Intelligence",
      "category": "AI",
      "description": "Siri、听写、云端计算与 AI 扩展的 5 个精确主机。",
      "policyLabel": "按已有 AI 策略选择出口",
      "warning": "也影响普通 Siri/听写；只决定网络出口，不能改变设备、账号、销售地区或语言资格。",
      "path": "ruleset/SiriAI.yaml",
      "policy": "🤖 AI 服务",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/SiriAI.yaml",
      "sourceUrl": "https://github.com/BrownieCoder/proxy-rulesets/blob/main/ruleset/SiriAI.yaml",
      "guideUrl": "../services/siri-ai.html",
      "ruleCount": 5,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "openai",
      "provider": "OpenAI",
      "name": "ChatGPT / OpenAI",
      "category": "AI",
      "description": "ChatGPT、OpenAI 与相关连接服务。",
      "policyLabel": "按已有 OpenAI 策略选择出口",
      "warning": "包括第三方共用域名和 IP 段；可能影响其他使用这些服务的流量。",
      "path": "ruleset/OpenAI_No_Resolve.yaml",
      "policy": "🤖 OpenAI",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/OpenAI_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI_No_Resolve.yaml",
      "guideUrl": "../services/openai.html",
      "ruleCount": 35,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "claude",
      "provider": "Claude",
      "name": "Claude",
      "category": "AI",
      "description": "Claude 的上游基础规则。",
      "policyLabel": "按已有 Claude 策略选择出口",
      "warning": "此文件仅 3 条；完整方案在有序路由中还有 10 条补充。不能把复制此文件当作完整 Claude 配置。",
      "path": "ruleset/Claude_No_Resolve.yaml",
      "policy": "🧠 Claude",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/Claude_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude_No_Resolve.yaml",
      "guideUrl": "../services/claude.html",
      "ruleCount": 3,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "gemini",
      "provider": "Gemini",
      "name": "Gemini",
      "category": "AI",
      "description": "Gemini 与相关 Google AI 服务。",
      "policyLabel": "按已有 Gemini 策略选择出口",
      "warning": "包含 apis.google.com 和较宽关键词，可能影响非 Gemini 的 Google 流量。",
      "path": "ruleset/Gemini_No_Resolve.yaml",
      "policy": "♊ Gemini",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/Gemini_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini_No_Resolve.yaml",
      "guideUrl": "../services/gemini.html",
      "ruleCount": 13,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "international-gaming",
      "provider": "InternationalGaming",
      "name": "国际游戏",
      "category": "游戏",
      "description": "保护已确认的国际服、发行与游戏 SDK。",
      "policyLabel": "只选代理出口",
      "warning": "必须保留安全规则优先和 fastcdn.hoyoverse.com 直连例外，再放在中国游戏之前。",
      "path": "ruleset/InternationalGaming.yaml",
      "policy": "🎮 国际游戏",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/InternationalGaming.yaml",
      "sourceUrl": "https://github.com/BrownieCoder/proxy-rulesets/blob/main/ruleset/InternationalGaming.yaml",
      "guideUrl": "../services/international-gaming.html",
      "ruleCount": 25,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "china-gaming",
      "provider": "ChinaGaming",
      "name": "中国游戏",
      "category": "游戏",
      "description": "已确认的国服官网、登录、更新和下载服务。",
      "policyLabel": "直连",
      "warning": "必须放在安全规则和国际游戏之后；不是全球游戏通用直连规则。",
      "path": "ruleset/ChinaGaming.yaml",
      "policy": "DIRECT",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/ChinaGaming.yaml",
      "sourceUrl": "https://github.com/BrownieCoder/proxy-rulesets/blob/main/ruleset/ChinaGaming.yaml",
      "guideUrl": "../services/china-gaming.html",
      "ruleCount": 93,
      "module": null,
      "moduleReason": "依赖前置安全规则或其他分流，独立模块不能保持原顺序。"
    },
    {
      "id": "steam",
      "provider": "Steam",
      "name": "Steam",
      "category": "游戏",
      "description": "Steam 商店、社区与相关全球服务。",
      "policyLabel": "按已有 Steam 策略选择出口",
      "warning": "先保留中国游戏规则；此规则不能替代区服和下载节点判断。",
      "path": "ruleset/Steam_No_Resolve.yaml",
      "policy": "🕹️ Steam",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/Steam_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam_No_Resolve.yaml",
      "guideUrl": "../services/steam.html",
      "ruleCount": 54,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "steam-cn",
      "provider": "SteamCN",
      "name": "Steam 下载与蒸汽平台",
      "category": "游戏",
      "description": "上游 SteamCN 下载相关规则。",
      "policyLabel": "按已有 Steam 策略选择出口",
      "warning": "含全球共享 steamcontent.com，原方案没有把整个规则集固定直连。",
      "path": "ruleset/SteamCN_No_Resolve.yaml",
      "policy": "🕹️ Steam",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/SteamCN_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN_No_Resolve.yaml",
      "guideUrl": "../services/steam-cn.html",
      "ruleCount": 17,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "apple",
      "provider": "Apple",
      "name": "Apple 服务",
      "category": "Apple 与网络",
      "description": "Apple 通用网络服务。",
      "policyLabel": "默认直连，可选代理",
      "warning": "必须在 Siri AI 之后，避免先匹配其精确主机；包含进程和 IP 规则。",
      "path": "ruleset/Apple_No_Resolve.yaml",
      "policy": "🍎 Apple",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/Apple_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple_Classical_No_Resolve.yaml",
      "guideUrl": "../services/apple.html",
      "ruleCount": 1593,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "google",
      "provider": "Google",
      "name": "Google",
      "category": "Apple 与网络",
      "description": "Google 通用网络服务。",
      "policyLabel": "沿用已有 Google 策略",
      "warning": "必须在 Gemini 之后；包含较广域名、IP 和进程规则。",
      "path": "ruleset/Google_No_Resolve.yaml",
      "policy": "🔎 Google",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/Google_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google_No_Resolve.yaml",
      "guideUrl": "../services/google.html",
      "ruleCount": 701,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "microsoft",
      "provider": "Microsoft",
      "name": "Microsoft",
      "category": "Apple 与网络",
      "description": "Microsoft 通用网络服务。",
      "policyLabel": "沿用已有 Microsoft 策略",
      "warning": "包含较广域名和进程规则。",
      "path": "ruleset/Microsoft_No_Resolve.yaml",
      "policy": "🪟 Microsoft",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/Microsoft_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft_No_Resolve.yaml",
      "guideUrl": "../services/microsoft.html",
      "ruleCount": 670,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "youtube",
      "provider": "YouTube",
      "name": "YouTube",
      "category": "影音",
      "description": "YouTube 视频及相关资源。",
      "policyLabel": "按已有国际媒体策略选择出口",
      "warning": "共享资源域名和 IP 规则可能承接其他流量。",
      "path": "ruleset/YouTube_No_Resolve.yaml",
      "policy": "📼 YouTube",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/YouTube_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube_No_Resolve.yaml",
      "guideUrl": "../services/youtube.html",
      "ruleCount": 183,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "bilibili",
      "provider": "Bilibili",
      "name": "哔哩哔哩",
      "category": "影音",
      "description": "哔哩哔哩服务。",
      "policyLabel": "默认直连，可选代理",
      "warning": "保持在国际游戏和中国游戏之后。",
      "path": "ruleset/Bilibili_No_Resolve.yaml",
      "policy": "📺 Bilibili",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/Bilibili_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili_No_Resolve.yaml",
      "guideUrl": "../services/bilibili.html",
      "ruleCount": 129,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "tiktok",
      "provider": "TikTok",
      "name": "TikTok",
      "category": "影音",
      "description": "TikTok 内容及相关网络服务。",
      "policyLabel": "按已有国际媒体策略选择出口",
      "warning": "分流不改变账号或地区资格；含进程规则。",
      "path": "ruleset/TikTok_No_Resolve.yaml",
      "policy": "🎵 Tiktok",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/TikTok_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok_No_Resolve.yaml",
      "guideUrl": "../services/tiktok.html",
      "ruleCount": 32,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "disney",
      "provider": "Disney",
      "name": "Disney+",
      "category": "影音",
      "description": "Disney+ 及相关媒体资源。",
      "policyLabel": "按已有国际媒体策略选择出口",
      "warning": "分流不保证地区可用；含进程规则。",
      "path": "ruleset/Disney_No_Resolve.yaml",
      "policy": "🏰 Disney",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/Disney_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney_No_Resolve.yaml",
      "guideUrl": "../services/disney.html",
      "ruleCount": 174,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "netflix",
      "provider": "Netflix",
      "name": "Netflix",
      "category": "影音",
      "description": "Netflix 内容及相关资源。",
      "policyLabel": "按已有国际媒体策略选择出口",
      "warning": "分流不保证地区可用；含进程规则。",
      "path": "ruleset/Netflix_No_Resolve.yaml",
      "policy": "🎞️ Netflix",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/Netflix_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix_No_Resolve.yaml",
      "guideUrl": "../services/netflix.html",
      "ruleCount": 38,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "global-media",
      "provider": "GlobalMedia",
      "name": "其他国际媒体",
      "category": "影音",
      "description": "现有上游国际媒体集合。",
      "policyLabel": "按已有国际媒体策略选择出口",
      "warning": "范围较广，必须放在游戏和具体服务之后。",
      "path": "ruleset/GlobalMedia_Classical_No_Resolve.yaml",
      "policy": "🛰️ International-Global",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/GlobalMedia_Classical_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Classical_No_Resolve.yaml",
      "guideUrl": "../services/global-media.html",
      "ruleCount": 2265,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "telegram",
      "provider": "Telegram",
      "name": "Telegram",
      "category": "社交",
      "description": "Telegram 网络连接与资源。",
      "policyLabel": "沿用已有 Telegram 策略",
      "warning": "包含 IP、ASN 和进程规则，不能仅凭域名列表代表全部行为。",
      "path": "ruleset/Telegram_No_Resolve.yaml",
      "policy": "✈️ Telegram",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/Telegram_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram_No_Resolve.yaml",
      "guideUrl": "../services/telegram.html",
      "ruleCount": 46,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "twitter",
      "provider": "Twitter",
      "name": "X / Twitter",
      "category": "社交",
      "description": "X / Twitter 服务及媒体资源。",
      "policyLabel": "沿用已有 Twitter 策略",
      "warning": "包含域名与 IP 规则。",
      "path": "ruleset/Twitter_No_Resolve.yaml",
      "policy": "🕊️ Twitter",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/Twitter_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter_No_Resolve.yaml",
      "guideUrl": "../services/twitter.html",
      "ruleCount": 33,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "discord",
      "provider": "Discord",
      "name": "Discord",
      "category": "社交",
      "description": "Discord 语音、聊天及相关资源。",
      "policyLabel": "沿用已有 Discord 策略",
      "warning": "实际语音出口还取决于节点和 UDP 能力。",
      "path": "ruleset/Discord_No_Resolve.yaml",
      "policy": "👾 Discord",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/Discord_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Discord/Discord_No_Resolve.yaml",
      "guideUrl": "../services/discord.html",
      "ruleCount": 29,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "paypal",
      "provider": "PayPal",
      "name": "PayPal",
      "category": "支付与其他",
      "description": "PayPal 网络服务。",
      "policyLabel": "按已有支付策略选择出口",
      "warning": "网络分流不保证交易、风控或地区可用。",
      "path": "ruleset/PayPal_No_Resolve.yaml",
      "policy": "💳 Payment",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/PayPal_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal_No_Resolve.yaml",
      "guideUrl": "../services/paypal.html",
      "ruleCount": 247,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "stripe",
      "provider": "Stripe",
      "name": "Stripe",
      "category": "支付与其他",
      "description": "含 stripe 关键词的网络请求。",
      "policyLabel": "按已有支付策略选择出口",
      "warning": "这是现有关键词规则，可能匹配非 Stripe 官方主机。",
      "path": "ruleset/Stripe_No_Resolve.yaml",
      "policy": "💳 Payment",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/Stripe_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Stripe/Stripe_No_Resolve.yaml",
      "guideUrl": "../services/stripe.html",
      "ruleCount": 1,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "crypto",
      "provider": "Crypto",
      "name": "加密资产服务",
      "category": "支付与其他",
      "description": "上游加密资产服务集合。",
      "policyLabel": "按已有 Crypto 策略选择出口",
      "warning": "包含多个服务和进程规则；不提供交易建议。",
      "path": "ruleset/Crypto_No_Resolve.yaml",
      "policy": "🪙 Crypto",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/Crypto_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Crypto/Crypto_No_Resolve.yaml",
      "guideUrl": "../services/crypto.html",
      "ruleCount": 204,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "crypto-web",
      "provider": "CryptoWeb",
      "name": "加密资产网页补充",
      "category": "支付与其他",
      "description": "本地维护的加密资产网页补充。",
      "policyLabel": "按已有 Crypto 策略选择出口",
      "warning": "与上游 Crypto 互补，保留原有策略。",
      "path": "ruleset/Crypto.yaml",
      "policy": "🪙 Crypto",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/Crypto.yaml",
      "sourceUrl": "https://github.com/BrownieCoder/proxy-rulesets/blob/main/ruleset/Crypto.yaml",
      "guideUrl": "../services/crypto-web.html",
      "ruleCount": 2,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "privacy",
      "provider": "Privacy",
      "name": "隐私拦截",
      "category": "安全与基础",
      "description": "拦截现有上游隐私追踪清单中的连接。",
      "policyLabel": "拒绝连接",
      "warning": "可能阻止依赖这些域名的网站功能；模块高于主配置，关闭模块即可撤销本模块。",
      "path": "ruleset/Privacy_No_Resolve.yaml",
      "policy": "REJECT",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/Privacy_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy_Classical_No_Resolve.yaml",
      "guideUrl": "../services/privacy.html",
      "ruleCount": 39936,
      "module": {
        "path": "modules/privacy.module",
        "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/modules/privacy.module",
        "schemeUrl": "shadowrocket://install?module=https%3A%2F%2Fraw.githubusercontent.com%2FBrownieCoder%2Fproxy-rulesets%2Fmain%2Fmodules%2Fprivacy.module",
        "published": false
      },
      "moduleReason": ""
    },
    {
      "id": "hijacking",
      "provider": "Hijacking",
      "name": "劫持拦截",
      "category": "安全与基础",
      "description": "现有上游劫持防护清单。",
      "policyLabel": "默认拒绝，可选直连",
      "warning": "原方案允许手动选择直连，不能简化为固定拒绝模块。",
      "path": "ruleset/Hijacking_No_Resolve.yaml",
      "policy": "🚫 Hijacking",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/Hijacking_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hijacking/Hijacking_No_Resolve.yaml",
      "guideUrl": "../services/hijacking.html",
      "ruleCount": 228,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "china-max",
      "provider": "ChinaMax",
      "name": "中国网络",
      "category": "安全与基础",
      "description": "上游中国网络综合集合。",
      "policyLabel": "默认直连，可选代理",
      "warning": "范围很广，必须放在安全、游戏、具体服务与国际媒体之后。",
      "path": "ruleset/ChinaMax_Classical_No_Resolve.yaml",
      "policy": "🇨🇳 China-Global",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/ChinaMax_Classical_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Classical_No_Resolve.yaml",
      "guideUrl": "../services/china-max.html",
      "ruleCount": 123815,
      "module": null,
      "moduleReason": "原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。"
    },
    {
      "id": "lan",
      "provider": "Lan",
      "name": "本地网络",
      "category": "安全与基础",
      "description": "现有局域网和保留地址规则。",
      "policyLabel": "直连",
      "warning": "原方案位于 ChinaMax 之后；不可提升为覆盖前面规则的直连模块。",
      "path": "ruleset/Lan_No_Resolve.yaml",
      "policy": "DIRECT",
      "rawUrl": "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main/ruleset/Lan_No_Resolve.yaml",
      "sourceUrl": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan_No_Resolve.yaml",
      "guideUrl": "../services/lan.html",
      "ruleCount": 140,
      "module": null,
      "moduleReason": "依赖前置安全规则或其他分流，独立模块不能保持原顺序。"
    }
  ],
  "clients": [
    {
      "id": "shadowrocket",
      "name": "Shadowrocket",
      "platform": "iPhone / iPad",
      "mode": "module",
      "summary": "依据社区手册生成隐私拦截模块，条目与拒绝目标一致；跨客户端命中未真机验证，模块尚未发布。其他服务请手动配置。",
      "fallback": [
        "先看对应服务教程，确认是否提供已发布模块。",
        "有模块时打开「配置 → 当前配置 → 模块 → 添加模块」。",
        "粘贴模块地址并启用；没有模块则按教程手动配置。"
      ],
      "guideUrl": "../docs/clients/shadowrocket.html"
    },
    {
      "id": "clashx-meta",
      "name": "ClashX.Meta",
      "platform": "macOS",
      "mode": "manual",
      "summary": "复制的是规则地址，不能粘贴到远程配置入口。完整配置导入会切换，同名可能替换；不自动合并。",
      "fallback": [
        "复制下方规则地址。",
        "打开教程，在当前配置的规则集合位置填写地址。",
        "关联已有策略并核对顺序，检查配置后启用。"
      ],
      "guideUrl": "../docs/clients/mihomo.html#clashxmeta"
    },
    {
      "id": "clash-verge",
      "name": "Clash Verge Rev",
      "platform": "Windows / macOS / Linux",
      "mode": "manual",
      "summary": "规则地址不是订阅地址。完整配置导入一般新增配置；没有当前配置时可能启用；不自动合并规则。",
      "fallback": [
        "复制下方规则地址。",
        "打开教程，在当前配置的覆写中添加规则集合。",
        "关联已有策略并核对顺序，检查配置后启用。"
      ],
      "guideUrl": "../docs/clients/mihomo.html#clash-verge-rev"
    },
    {
      "id": "clash-party",
      "name": "Clash Party · 原 Mihomo Party",
      "platform": "Windows / macOS / Linux",
      "mode": "manual",
      "summary": "规则地址不是订阅地址。v2.0.3 完整配置导入通常新增；无当前配置时启用；不自动合并规则。",
      "fallback": [
        "复制下方规则地址。",
        "打开教程，在目标配置的覆写中添加规则集合。",
        "关联已有策略并核对顺序，检查配置后启用。"
      ],
      "guideUrl": "../docs/clients/mihomo.html#clash-party"
    },
    {
      "id": "mihomo",
      "name": "其他 Mihomo 客户端",
      "platform": "按具体 App 确认",
      "mode": "manual",
      "summary": "Mihomo 是内核。各 App 的编辑入口不同，没有通用的规则一键导入链接。",
      "fallback": [
        "复制下方规则地址。",
        "打开通用教程，将规则集合接入当前配置。",
        "关联已有策略并核对顺序，检查配置后启用。"
      ],
      "guideUrl": "../docs/clients/mihomo.html"
    }
  ]
};
