#!/usr/bin/env python3
"""Generate/check the GitHub-native service catalog offline. No downloads or private inputs."""
from __future__ import annotations

import argparse
import hashlib
import ipaddress
import json
import re
from pathlib import Path

from siri_ai import canonical as siri_canonical, render as siri_render
from sync import render_provider_configs

ROOT = Path(__file__).resolve().parents[1]
START = '<!-- SERVICE-CATALOG:START -->'
END = '<!-- SERVICE-CATALOG:END -->'
DOMAIN = re.compile(r'[A-Za-z0-9_](?:[A-Za-z0-9_-]{0,61}[A-Za-z0-9_])?(?:\.[A-Za-z0-9_](?:[A-Za-z0-9_-]{0,61}[A-Za-z0-9_])?)*\Z')
KINDS = {'DOMAIN', 'DOMAIN-SUFFIX', 'DOMAIN-KEYWORD', 'IP-CIDR', 'IP-CIDR6', 'IP-ASN', 'PROCESS-NAME'}


def json_text(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2) + '\n'


def load(root: Path, path: str):
    return json.loads((root / path).read_text(encoding='utf-8'))


def digest(text: str) -> str:
    return hashlib.sha256(text.encode('utf-8')).hexdigest()


def check_rule(rule: str) -> None:
    fields = rule.split(',')
    kind = fields[0]
    if kind not in KINDS or len(fields) not in (2, 3) or not fields[1]:
        raise ValueError(f'Unsupported rule syntax: {rule}')
    if len(fields) == 3 and (fields[2] != 'no-resolve' or kind not in {'IP-CIDR', 'IP-CIDR6', 'IP-ASN'}):
        raise ValueError(f'Unsupported rule options: {rule}')
    value = fields[1]
    if kind in {'DOMAIN', 'DOMAIN-SUFFIX'}:
        if len(value) > 253 or not DOMAIN.fullmatch(value):
            raise ValueError(f'Invalid domain: {value}')
    elif kind in {'IP-CIDR', 'IP-CIDR6'}:
        network = ipaddress.ip_network(value, strict=False)
        if network.version != (4 if kind == 'IP-CIDR' else 6):
            raise ValueError(f'Wrong IP version: {rule}')
    elif kind == 'IP-ASN':
        if not value.isdecimal() or not 0 < int(value) <= 4294967295:
            raise ValueError(f'Invalid ASN: {rule}')
    elif any(c in value for c in '\r\n#[]'):
        raise ValueError(f'Invalid rule value: {rule}')


def read_rules(text: str) -> list[str]:
    """Parse the repository's deliberately restricted classical YAML subset."""
    rules = []
    payload = False
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        if line == 'payload:' and not payload:
            payload = True
            continue
        if not payload or not line.startswith('- '):
            raise ValueError('Expected one payload mapping with scalar rule entries')
        rule = line[2:]
        if rule.startswith(('"', "'")):
            if len(rule) < 2 or rule[-1] != rule[0]:
                raise ValueError('Unbalanced YAML quotes')
            rule = rule[1:-1]
        check_rule(rule)
        rules.append(rule)
    if not rules or len(rules) != len(set(rules)):
        raise ValueError('Empty or duplicate rules')
    return rules


def routing(root: Path) -> tuple[list[str], dict[str, str]]:
    ordered = [line.strip()[2:] for line in (root / 'config/rules.yaml').read_text().splitlines()
               if line.strip().startswith('- ')]
    targets = {}
    for rule in ordered:
        fields = rule.split(',')
        if fields[0] == 'RULE-SET':
            if fields[1] in targets:
                raise ValueError('Duplicate provider reference')
            targets[fields[1]] = fields[2]
    if ordered[0] != 'RULE-SET,Privacy,REJECT':
        raise ValueError('Privacy must retain its first, fixed REJECT routing')
    return ordered, targets


def service_page(s: dict) -> str:
    return f'''<!-- Generated by scripts/generate_catalog.py; do not edit. -->
# {s['name']}

[返回服务目录](../README.md#服务目录) · [查看规则文件](../{s['path']})

{s['description']}

## 规则地址

复制下面这一行公开地址；也可右键或长按[原始文件链接]({s['rawUrl']})复制链接。

```text
{s['rawUrl']}
```

本页只提供规则文件地址，复制或下载不会修改你已有的配置。文件不包含节点、订阅或凭证。

## 作用与范围

推荐：**{s['policyLabel']}**。现有规则目标：`{s['policy']}`。共 **{s['ruleCount']} 条**规则。

{s['warning']}

单个文件不包含完整分流方案中的前置保护和补充规则；组合使用时参考[有序规则](../config/rules.yaml)与[高级说明](../docs/advanced.md)。

## 来源

[{s['provider']} 的公开来源]({s['sourceUrl']}) · [署名与许可](../THIRD_PARTY_NOTICES.md)

如有规则问题，请提供脱敏后的域名、预期结果和实际结果，不要上传完整私人配置。
'''


def build(root: Path = ROOT) -> dict[str, str]:
    sources = load(root, 'sources.json')
    local = load(root, 'local-rulesets.json')
    providers = {**sources, **local}
    catalog = load(root, 'catalog/services.json')
    repo, branch = 'BrownieCoder/proxy-rulesets', 'main'
    raw_base = f'https://raw.githubusercontent.com/{repo}/{branch}'
    blob_base = f'https://github.com/{repo}/blob/{branch}'
    ids = [s['id'] for s in catalog]
    names = [s['provider'] for s in catalog]
    if len(set(ids)) != len(ids) or any(not re.fullmatch('[a-z0-9]+(?:-[a-z0-9]+)*', i) for i in ids):
        raise ValueError('Duplicate/invalid service id')
    if len(names) != len(set(names)) or set(names) != set(providers):
        raise ValueError('Service catalog must cover every provider exactly once')
    _, targets = routing(root)
    if set(targets) != set(providers):
        raise ValueError('Catalog target must come from existing routing contract')
    # Keep the existing provider generation and validation contract in the same
    # candidate build used by sync.py; catalog simplification must not drop it.
    output = render_provider_configs(sources, local)
    domains, siri_hash = siri_canonical(root)
    if (root / local['SiriAI']['path']).read_text() != siri_render(domains, siri_hash):
        raise ValueError('Siri canonical/provider drift; use existing siri_ai.py --write')
    services = []
    records = {}
    for entry in catalog:
        for field in ('name', 'category', 'description', 'policyLabel', 'warning'):
            if not entry.get(field) or '\n' in entry[field] or '|' in entry[field]:
                raise ValueError(f'Invalid service field: {field}')
        name = entry['provider']
        record = providers[name]
        path = record['path']
        if not path.startswith('ruleset/') or '..' in Path(path).parts or not (root / path).is_file():
            raise ValueError('Missing/unsafe provider path')
        if record.get('behavior', 'classical') != 'classical':
            raise ValueError('Only existing classical format has been reviewed')
        source = (root / path).read_bytes().decode('utf-8')
        rules = read_rules(source)
        service = {**entry, 'path': path, 'policy': targets[name], 'rawUrl': f'{raw_base}/{path}',
                   'sourceUrl': record.get('url', f'{blob_base}/{path}'),
                   'page': f'services/{entry["id"]}.md', 'ruleCount': len(rules)}
        services.append(service)
        records[path] = {'sha256': digest(source), 'rulesSha256': digest('\n'.join(rules) + '\n'), 'ruleCount': len(rules)}
        output[service['page']] = service_page(service)
    output['catalog/index.json'] = json_text({'repository': repo, 'branch': branch, 'services': services})
    table = []
    categories = list(dict.fromkeys(s['category'] for s in services))
    table += [' · '.join(f'[{category}](#{category.lower().replace(" ", "-")})' for category in categories), '']
    for category in categories:
        table += [f'### {category}', '', '| 服务 | 作用 | 获取 |', '| --- | --- | --- |']
        for service in services:
            if service['category'] != category:
                continue
            table.append(f'| [{service["name"]}]({service["page"]}) | {service["description"]} | [获取地址]({service["page"]}#规则地址) · [查看规则]({service["path"]}) |')
        table += ['']
    readme = (root / 'README.md').read_text()
    if readme.count(START) != 1 or readme.count(END) != 1:
        raise ValueError('README needs exactly one generated service catalog region')
    before, tail = readme.split(START)
    _, after = tail.split(END)
    table_text = '\n'.join(table)
    output['README.md'] = before + START + '\n' + table_text + END + after
    output['catalog/assets.lock.json'] = json_text({
        'sources': records,
        'readmeCatalogSha256': digest(table_text),
        'artifacts': {p: digest(t) for p, t in output.items() if p != 'README.md'},
    })
    return output


def generate(root: Path = ROOT, write: bool = False) -> dict[str, str]:
    output = build(root)
    stale = [str(p.relative_to(root)) for p in (root / 'services').glob('*.md') if str(p.relative_to(root)) not in output]
    if stale:
        raise ValueError('Unexpected generated files; review before removing: ' + ', '.join(stale))
    differences = []
    for relative, content in output.items():
        path = root / relative
        if write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8')
        elif not path.is_file() or path.read_bytes() != content.encode('utf-8'):
            differences.append(relative)
    if differences:
        raise ValueError('Generated drift; run scripts/generate_catalog.py --write: ' + ', '.join(differences))
    print(f'GitHub catalog: {len(load(root, "catalog/services.json"))} services; rules/hash/provider/document consistency passed.')
    return output


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true', help='regenerate repository documents without network access')
    args = parser.parse_args()
    generate(write=args.write)


if __name__ == '__main__':
    main()
