#!/usr/bin/env python3
"""Generate/check public install assets offline. No downloads or private inputs."""
from __future__ import annotations

import argparse
import hashlib
import ipaddress
import json
import re
from pathlib import Path
from urllib.parse import quote
from render_install_docs import render as render_doc

from siri_ai import canonical as siri_canonical, render as siri_render
from sync import render_provider_configs

ROOT = Path(__file__).resolve().parents[1]
START = '<!-- INSTALL-TABLE:START -->'
END = '<!-- INSTALL-TABLE:END -->'
DOMAIN = re.compile(r'[A-Za-z0-9_](?:[A-Za-z0-9_-]{0,61}[A-Za-z0-9_])?(?:\.[A-Za-z0-9_](?:[A-Za-z0-9_-]{0,61}[A-Za-z0-9_])?)*\Z')
KINDS = {'DOMAIN', 'DOMAIN-SUFFIX', 'DOMAIN-KEYWORD', 'IP-CIDR', 'IP-CIDR6', 'IP-ASN', 'PROCESS-NAME'}


def json_text(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2) + '\n'


def load(root: Path, path: str):
    return json.loads((root / path).read_text(encoding='utf-8'))


def digest(text: str) -> str:
    return hashlib.sha256(text.encode('utf-8')).hexdigest()


def check_rule(rule: str) -> None:
    fields = rule.split(',')
    kind = fields[0]
    if kind not in KINDS or len(fields) not in (2, 3) or not fields[1]:
        raise ValueError(f'Unsupported rule syntax: {rule}')
    if len(fields) == 3 and (fields[2] != 'no-resolve' or kind not in {'IP-CIDR', 'IP-CIDR6', 'IP-ASN'}):
        raise ValueError(f'Unsupported rule options: {rule}')
    value = fields[1]
    if kind in {'DOMAIN', 'DOMAIN-SUFFIX'}:
        if len(value) > 253 or not DOMAIN.fullmatch(value):
            raise ValueError(f'Invalid domain: {value}')
    elif kind in {'IP-CIDR', 'IP-CIDR6'}:
        network = ipaddress.ip_network(value, strict=False)
        if network.version != (4 if kind == 'IP-CIDR' else 6):
            raise ValueError(f'Wrong IP version: {rule}')
    elif kind == 'IP-ASN':
        if not value.isdecimal() or not 0 < int(value) <= 4294967295:
            raise ValueError(f'Invalid ASN: {rule}')
    elif any(c in value for c in '\r\n#[]'):
        raise ValueError(f'Invalid rule value: {rule}')


def read_rules(text: str) -> list[str]:
    """Parse the repository's deliberately restricted classical YAML subset."""
    rules = []
    payload = False
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        if line == 'payload:' and not payload:
            payload = True
            continue
        if not payload or not line.startswith('- '):
            raise ValueError('Expected one payload mapping with scalar rule entries')
        rule = line[2:]
        if rule.startswith(('"', "'")):
            if len(rule) < 2 or rule[-1] != rule[0]:
                raise ValueError('Unbalanced YAML quotes')
            rule = rule[1:-1]
        check_rule(rule)
        rules.append(rule)
    if not rules or len(rules) != len(set(rules)):
        raise ValueError('Empty or duplicate rules')
    return rules


def routing(root: Path) -> tuple[list[str], dict[str, str]]:
    ordered = [line.strip()[2:] for line in (root / 'config/rules.yaml').read_text().splitlines()
               if line.strip().startswith('- ')]
    targets = {}
    for rule in ordered:
        fields = rule.split(',')
        if fields[0] == 'RULE-SET':
            if fields[1] in targets:
                raise ValueError('Duplicate provider reference')
            targets[fields[1]] = fields[2]
    if ordered[0] != 'RULE-SET,Privacy,REJECT':
        raise ValueError('Standalone Privacy module requires first, fixed REJECT routing')
    return ordered, targets


def module_reason(provider: str, target: str, rules: list[str]) -> str:
    if provider == 'Privacy':
        if target != 'REJECT' or any(r.split(',')[0] not in {'DOMAIN', 'DOMAIN-SUFFIX', 'DOMAIN-KEYWORD', 'IP-CIDR'} for r in rules):
            raise ValueError('Privacy module contract needs a new compatibility review')
        return ''
    if target in {'DIRECT', 'REJECT'}:
        return '依赖前置安全规则或其他分流，独立模块不能保持原顺序。'
    return '原策略允许选择出口，固定代理模块不能保留这些选择；还须保留前置规则。'


def shadowrocket_url(raw_url: str) -> str:
    return 'shadowrocket://install?module=' + quote(raw_url, safe='')


def render_module(source: str, rules: list[str], path: str, source_url: str) -> str:
    attribution = [line for line in source.splitlines() if line.startswith('#')]
    lines = [
        '#!name=Proxy Rulesets - 隐私拦截',
        '#!desc=固定拒绝清单；不替换节点或主配置，模块规则优先。关闭模块可撤销。',
        '# Generated by scripts/generate_install_assets.py; do not edit.',
        '# Source: ' + path, '# Upstream: ' + source_url,
        '# Source-SHA256: ' + digest(source),
        '# Rules-SHA256: ' + digest('\n'.join(rules) + '\n'),
        '# Attribution/license: ../THIRD_PARTY_NOTICES.md; GPL-2.0 and upstream statements.',
        *attribution, '', '[Rule]',
    ]
    for rule in rules:
        fields = rule.split(',')
        lines.append(','.join(fields[:2] + ['REJECT'] + fields[2:]))
    return '\n'.join(lines) + '\n'


def service_page(service: dict, repo: str, branch: str) -> str:
    s = service
    module = s['module']
    if module:
        if module['published']:
            sr = f"[一键导入 Shadowrocket]({module['schemeUrl']}) · [复制模块地址]({module['rawUrl']})"
        else:
            sr = '**模块已生成，尚未发布，暂不能一键导入。** [查看本地模块](../modules/privacy.module)。'
        sr += '\n\n不替换节点或主配置；模块规则优先于主配置，可能拦截原本允许的连接。关闭模块可撤销。\n\n自动打开失败？①复制已发布的模块地址；②打开「配置 → 当前配置 → 模块 → 添加模块」；③粘贴并启用。发布前请按[本地教程](../docs/clients/shadowrocket.md)验证。'
    else:
        sr = '**需要手动配置。** ' + s['moduleReason'] + ' 不提供伪装成模块的 Mihomo 文件。请看[小火箭教程](../docs/clients/shadowrocket.md)。'
    return f'''<!-- Generated by scripts/generate_install_assets.py; do not edit. -->
# {s['name']}

[返回服务目录](../README.md#选择服务) · [安装中心源码/本地预览](../install/index.html)

{s['description']}

推荐：**{s['policyLabel']}**。对应现有策略：`{s['policy']}`。

## Shadowrocket

{sr}

## Clash / Mihomo

[ClashX.Meta](../docs/clients/mihomo.md#clashxmeta) · [Clash Verge Rev](../docs/clients/mihomo.md#clash-verge-rev) · [Clash Party](../docs/clients/mihomo.md#clash-party)

[规则地址]({s['rawUrl']})：

```text
{s['rawUrl']}
```

这是规则文件，**不是订阅或完整配置**。不会自动合并当前配置，请勿粘贴到「导入订阅」入口。

1. 复制上面的规则地址。
2. 按[客户端教程](../docs/clients/mihomo.md)在当前配置中接入规则集合。
3. 选择已有策略、核对顺序，检查后启用。

手动编辑会改变当前配置，请先备份；完整配置导入与加规则是不同操作，ClashX.Meta 同名远程配置导入可能替换旧配置。

## 会影响其他流量吗？

{s['warning']}

[完整有序方案](../config/rules.yaml)保留安全拦截优先、国际游戏先于中国游戏、具体服务先于宽泛规则。单个文件不包含这些前置保护和补充规则。

## 来源与问题排查

现有来源：[{s['provider']}]({s['sourceUrl']})；本地文件 [{s['path']}](../{s['path']})；共 {s['ruleCount']} 条。保留[第三方署名及许可](../THIRD_PARTY_NOTICES.md)。

规则未生效时，先确认使用的是编辑后的配置，再检查更早的规则和节点能力。不要上传完整配置、节点或账号资料。格式兼容和客户端版本依据见[能力研究](../docs/maintainer/client-capabilities.md)。
'''


def build(root: Path = ROOT) -> dict[str, str]:
    sources = load(root, 'sources.json')
    local = load(root, 'local-rulesets.json')
    providers = {**sources, **local}
    catalog = load(root, 'catalog/services.json')
    clients = load(root, 'catalog/clients.json')
    publication = load(root, 'catalog/publication.json')
    repo, branch = publication['repository'], publication['branch']
    if (repo, branch) != ('BrownieCoder/proxy-rulesets', 'main'):
        raise ValueError('Repository/default branch change needs explicit link verification')
    raw_base = f'https://raw.githubusercontent.com/{repo}/{branch}'
    blob_base = f'https://github.com/{repo}/blob/{branch}'
    ids = [s['id'] for s in catalog]
    names = [s['provider'] for s in catalog]
    if len(set(ids)) != len(ids) or any(not re.fullmatch('[a-z0-9]+(?:-[a-z0-9]+)*', i) for i in ids):
        raise ValueError('Duplicate/invalid service id')
    if len(names) != len(set(names)) or set(names) != set(providers):
        raise ValueError('Service catalog must cover every provider exactly once')
    if len({c['id'] for c in clients}) != len(clients):
        raise ValueError('Duplicate client id')
    for c in clients:
        if c['mode'] not in {'module', 'manual'} or len(c['fallback']) != 3:
            raise ValueError('Invalid client action/fallback')
        guide = (root / 'install' / c['guideUrl'].split('#')[0]).resolve()
        if not guide.is_relative_to(root.resolve()) or not guide.is_file():
            raise ValueError('Missing client guide')
    ordered, targets = routing(root)
    if set(targets) != set(providers):
        raise ValueError('Catalog target must come from existing routing contract')
    output = render_provider_configs(sources, local)
    domains, siri_hash = siri_canonical(root)
    siri_text = siri_render(domains, siri_hash)
    if (root / local['SiriAI']['path']).read_text() != siri_text:
        raise ValueError('Siri canonical/provider drift; use existing siri_ai.py --write')
    services = []
    records = {}
    expected_modules = set()
    for entry in catalog:
        for field in ('name', 'category', 'description', 'policyLabel', 'warning'):
            if not entry.get(field) or '\n' in entry[field] or '|' in entry[field]:
                raise ValueError(f'Invalid service field: {field}')
        name = entry['provider']
        record = providers[name]
        path = record['path']
        if not path.startswith('ruleset/') or '..' in Path(path).parts or not (root / path).is_file():
            raise ValueError('Missing/unsafe provider path')
        if record.get('behavior', 'classical') != 'classical':
            raise ValueError('Only existing classical format has been reviewed')
        source = (root / path).read_bytes().decode('utf-8')
        rules = read_rules(source)
        target = targets[name]
        source_url = record.get('url', f'{blob_base}/{path}')
        reason = module_reason(name, target, rules)
        s = {**entry, 'path': path, 'policy': target, 'rawUrl': f'{raw_base}/{path}',
             'sourceUrl': source_url, 'guideUrl': f'../services/{entry["id"]}.html',
             'ruleCount': len(rules), 'module': None, 'moduleReason': reason}
        records[path] = {'sha256': digest(source), 'rulesSha256': digest('\n'.join(rules) + '\n'), 'ruleCount': len(rules)}
        if not reason:
            module_path = f'modules/{entry["id"]}.module'
            expected_modules.add(module_path)
            output[module_path] = render_module(source, rules, path, source_url)
            published = module_path in publication['publishedModules']
            url = f'{raw_base}/{module_path}'
            s['module'] = {'path': module_path, 'rawUrl': url, 'schemeUrl': shadowrocket_url(url), 'published': published}
        services.append(s)
        output[f'services/{entry["id"]}.md'] = service_page(s, repo, branch)
    if not set(publication['publishedModules']) <= expected_modules:
        raise ValueError('Publication refers to an unsupported module')
    site = publication['siteUrl']
    if site is not None and site != 'https://browniecoder.github.io/proxy-rulesets/install/':
        raise ValueError('Unexpected site URL; verify hosting before changing publication metadata')
    # A published flag is a release gate, not a guess based on existence in the worktree.
    if publication['publishedModules'] or site:
        verification = load(root, 'catalog/online-verification.json')
        verified = {r['url']: r for r in verification['results']}
        for module_path in publication['publishedModules']:
            record = verified.get(f'{raw_base}/{module_path}', {})
            if record.get('status') != 200 or not re.fullmatch('[0-9a-f]{64}', record.get('sha256', '')):
                raise ValueError('Published module requires recorded successful online GET evidence')
        if site and verified.get(site, {}).get('status') != 200:
            raise ValueError('Published site requires a successful online GET')
    for client in clients:
        client['guideUrl'] = client['guideUrl'].replace('.md', '.html')
    data = {'repository': repo, 'branch': branch, 'siteUrl': site, 'services': services, 'clients': clients}
    output['install/catalog.json'] = json_text(data)
    output['install/catalog.js'] = '// Generated; no network or private inputs.\nwindow.INSTALL_CATALOG = ' + json_text(data).rstrip() + ';\n'
    table = []
    for category in dict.fromkeys(s['category'] for s in services):
        table += [f'### {category}', '', '| 服务 | 作用与推荐 | Shadowrocket | ClashX.Meta | Clash Verge Rev / Mihomo | 原始规则 |', '| --- | --- | --- | --- | --- | --- |']
        for s in services:
            if s['category'] != category:
                continue
            page = f'services/{s["id"]}.md'
            sr = '模块待发布' if s['module'] else '手动教程'
            if s['module'] and s['module']['published']:
                sr = '一键导入' if site else '模块教程'
            sr_url = (site + '?service=' + s['id'] + '&client=shadowrocket') if sr == '一键导入' else page + '#shadowrocket'
            table.append(f'| [{s["name"]}]({page}) | {s["description"]} {s["policyLabel"]} | [{sr}]({sr_url}) | [教程]({page}#clash--mihomo) | [规则地址]({s["rawUrl"]}) | [查看]({s["path"]}) |')
        table += ['']
    readme = (root / 'README.md').read_text()
    if readme.count(START) != 1 or readme.count(END) != 1:
        raise ValueError('README needs exactly one generated table region')
    before, tail = readme.split(START)
    _, after = tail.split(END)
    output['README.md'] = before + START + '\n' + '\n'.join(table) + END + after
    guide_paths = ['docs/clients/shadowrocket.md', 'docs/clients/mihomo.md', 'docs/advanced.md']
    markdown_pages = {p: t for p, t in output.items() if p.startswith('services/') and p.endswith('.md')}
    markdown_pages.update({p: (root / p).read_text() for p in guide_paths})
    for path, content in markdown_pages.items():
        output[path[:-3] + '.html'] = render_doc(content, path, set(markdown_pages))
    lock = {'sources': records, 'artifacts': {p: digest(t) for p, t in output.items() if p != 'README.md'}}
    output['install/assets.lock.json'] = json_text(lock)
    return output


def generate(root: Path = ROOT, write: bool = False) -> dict[str, str]:
    output = build(root)
    stale = []
    for directory, pattern in [('modules', '*.module'), ('services', '*.md')]:
        stale += [str(p.relative_to(root)) for p in (root / directory).glob(pattern) if str(p.relative_to(root)) not in output]
    if stale:
        raise ValueError('Unexpected generated files; review before removing: ' + ', '.join(stale))
    differences = []
    for relative, content in output.items():
        path = root / relative
        if write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8')
        elif not path.is_file() or path.read_bytes() != content.encode('utf-8'):
            differences.append(relative)
    if differences:
        raise ValueError('Generated drift; run scripts/generate_install_assets.py --write: ' + ', '.join(differences))
    print(f'Install assets: {len(load(root, "catalog/services.json"))} services, 1 ordered rule-only module; rules/hash/provider/catalog consistency passed (client routing not device-tested).')
    return output


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true', help='regenerate local assets without network access')
    args = parser.parse_args()
    generate(write=args.write)


if __name__ == '__main__':
    main()
