#!/usr/bin/env python3
"""Atomically mirror and validate all configured Clash/Mihomo rulesets."""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import sys
import tempfile
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES_FILE = ROOT / "sources.json"
LOCAL_RULESETS_FILE = ROOT / "local-rulesets.json"
LOCK_FILE = ROOT / "sources.lock.json"
USER_AGENT = "proxy-rulesets-mirror/1.0"


def validate(name: str, data: bytes) -> None:
    if len(data) < 10:
        raise ValueError(f"{name}: response is unexpectedly short")
    text = data.decode("utf-8")
    meaningful = [line.strip() for line in text.splitlines() if line.strip() and not line.lstrip().startswith("#")]
    if not meaningful or meaningful[0] != "payload:":
        raise ValueError(f"{name}: expected a classical ruleset beginning with 'payload:'")
    if not any(line.startswith("- ") for line in meaningful[1:]):
        raise ValueError(f"{name}: ruleset contains no payload entries")


def normalize(source: dict[str, str], data: bytes) -> bytes:
    """Convert supported upstream formats to Mihomo's classical YAML format."""
    if source.get("source_format") != "surge":
        return data
    text = data.decode("utf-8")
    rules = [
        line.strip()
        for line in text.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    if not rules:
        raise ValueError("Surge ruleset contains no rules")
    header = [
        "# Normalized from an upstream Surge ruleset by scripts/sync.py.",
        "payload:",
    ]
    return ("\n".join(header + [f"  - {rule}" for rule in rules]) + "\n").encode("utf-8")


def render_provider_configs(sources: dict[str, dict[str, str]], local_sources: dict[str, dict[str, str]]) -> dict[str, str]:
    local_lines = [
        "# Generated by scripts/sync.py. Merge this mapping into your Mihomo config.",
        "rule-providers:",
    ]
    remote_lines = [
        "# Public provider URLs for BrownieCoder/proxy-rulesets.",
        "rule-providers:",
    ]
    raw_base = "https://raw.githubusercontent.com/BrownieCoder/proxy-rulesets/main"
    providers = dict(sources)
    providers.update(local_sources)
    for name, source in providers.items():
        path = source["path"]
        behavior = source.get("behavior", "classical")
        cache_path = f"./ruleset-cache/{Path(path).name}"
        local_lines.extend(
            [
                f"  {name}:",
                "    type: file",
                f"    behavior: {behavior}",
                f"    path: ./{path}",
            ]
        )
        remote_lines.extend(
            [
                f"  {name}:",
                "    type: http",
                f"    behavior: {behavior}",
                f"    url: {raw_base}/{path}",
                "    interval: 86400",
                f"    path: {cache_path}",
            ]
        )
    return {
        "config/rule-providers.local.yaml": "\n".join(local_lines) + "\n",
        "config/rule-providers.remote.yaml": "\n".join(remote_lines) + "\n",
    }


def write_provider_configs(sources: dict[str, dict[str, str]]) -> None:
    local_sources = json.loads(LOCAL_RULESETS_FILE.read_text(encoding="utf-8"))
    for name, content in render_provider_configs(sources, local_sources).items():
        path = ROOT / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main() -> int:
    sources = json.loads(SOURCES_FILE.read_text(encoding="utf-8"))
    if "--generate-only" in sys.argv[1:]:
        write_provider_configs(sources)
        print("Generated provider config files.")
        return 0
    stage = Path(tempfile.mkdtemp(prefix="proxy-rulesets-", dir=ROOT))
    records: dict[str, dict[str, object]] = {}
    try:
        for name, source in sources.items():
            request = urllib.request.Request(source["url"], headers={"User-Agent": USER_AGENT})
            try:
                with urllib.request.urlopen(request, timeout=45) as response:
                    upstream_data = response.read()
                    final_url = response.geturl()
            except (OSError, urllib.error.URLError) as exc:
                raise RuntimeError(f"{name}: download failed: {exc}") from exc
            data = normalize(source, upstream_data)
            validate(name, data)
            target = stage / source["path"]
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)
            records[name] = {
                "path": source["path"],
                "source_url": source["url"],
                "final_url": final_url,
                "bytes": len(data),
                "sha256": hashlib.sha256(data).hexdigest(),
                "upstream_sha256": hashlib.sha256(upstream_data).hexdigest(),
            }
            print(f"ok  {name:<14} {len(data):>9,} bytes")

        # Assemble a public-only candidate tree. Validate all derived formats
        # before replacing any current snapshot, lock, provider or install asset.
        for directory in ("catalog", "rules"):
            shutil.copytree(ROOT / directory, stage / directory)
        for relative in ("README.md", "sources.json", "local-rulesets.json",
                         "config/rules.yaml", "research/SiriAI-audit.json"):
            target = stage / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(ROOT / relative, target)
        local_sources = json.loads(LOCAL_RULESETS_FILE.read_text(encoding="utf-8"))
        for source in local_sources.values():
            target = stage / source["path"]
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(ROOT / source["path"], target)
        from generate_catalog import build
        outputs = build(stage)
        for relative, content in outputs.items():
            target = stage / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")

        writes = [source["path"] for source in sources.values()] + list(outputs)
        previous_lock = {}
        if LOCK_FILE.exists():
            previous_lock = json.loads(LOCK_FILE.read_text(encoding="utf-8"))
        if previous_lock.get("rulesets") != records:
            lock = {
                "synced_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
                "rulesets": records,
            }
            (stage / "sources.lock.json").write_text(
                json.dumps(lock, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            writes.append("sources.lock.json")
        # Preserve the existing per-file atomic replace after all validation.
        for relative in writes:
            target = ROOT / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            os.replace(stage / relative, target)
        print(f"\nSynced {len(records)} rulesets.")
        return 0
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    finally:
        shutil.rmtree(stage, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
